### PR TITLE
OS X fixes

### PR DESCRIPTION
**Pull request by mherb**

### CODE REVIEW

**Comment by Phibedy** [comment]
We use cmake. sorry
Plattformspecific code should be separated in another file.

**Comment by mherb** [comment]
It is _very_ common practice to handle platform specific code through ifdef's rather than separate files as this reduces copy-paste code.

Additionally, say you have to do platform specific typedefs in a header file, you cannot split out those parts in a separate file, so at some point ifdefs are needed anyways.

**Comment by Phibedy** [comment]
For bigger chunks, we use the buildsystem instead (foo.cpp foo_win.cpp, foo_unix.cpp); 
Little dependencies can be covered using #ifdefs
Indeed that's a common pratice for bigger projects too :)

**Comment by mherb** [comment]
I see, PR will be updated accordingly. stay tuned :)

**Comment by Phibedy** [comment]
Thanks :)

**Pull request closed without merging**
